### ISSUE TITLE
Need a way to easily downgrade firmware

### ISSUE THREAD

**Issue by hughsie** [hughsie/fwupd#10]
e.g.

    fwupdmgr downgrade UEFI-819b858e-aaaa-402f-bbbb-5b311b6c1959-dev0

I guess we need to allow the user to choose an older version of the firmware also.

**Comment by morhook** [comment]
Is there a way to mark an upgrade as non-installable? The BIOS 1.2.10 version for Dell XPS 15 9550 is producing a [brightness error](https://www.reddit.com/r/Dell/comments/4rhp38/xps_15_9550_bios_1210_display_flicker/) on my LCD 4k screen.

Is there any way to avoid installing this specific version of BIOS? With BIOS 1.2.0 my machine was working awesome, and `fwupd` is always suggesting to upgrade.
