### ISSUE TITLE
Support ChromeOS touchpad FW updater interface

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#106]
Many touchpad vendors have upstreamed drivers that were created from ChromeOS for touchpads.  These drivers happen to work even on non-Chromebook devices in many instances though too.

Google mandates the following interface for Touch Firmware Updater:
https://www.chromium.org/chromium-os/chromiumos-design-docs/touch-firmware-updater

Since this is just parsing some files in sysfs, I think this should likely be fairly easy to provide a fwupd plugin.

**Comment by hughsie** [comment]
Do you know of any hardware that works standalone that we can purchase? We'd also need a repo of firmware for testing. Thanks!

**Comment by superm1** [comment]
I don't know of any standalone touchpads, only those in laptops.  
The vendors I've talked to so far that already have ChromeOS touch firmware updater support would prefer to support via UEFI capsule long term though though.  So this might be irrelevant.

**Comment by superm1** [comment]
I'll close this since there isn't any vendor willing to back this for now.
