### ISSUE TITLE
fwupd.service after display-manager instead of after gdm

### ISSUE THREAD

**Issue by Thaodan** [hughsie/fwupd#1085]
Currently the systemd unit of systemd has After=gdm.service. Shouldn't it be better
if it was After=display-manager.service to work for other dms like SDDM too?

**Comment by superm1** [comment]
Seems reasonable enough to me.  Care to file a PR?

**Comment by Thaodan** [comment]
#1086 done.

**Comment by Thaodan** [comment]
fixed by https://github.com/hughsie/fwupd/commit/156538f1c396e68586c17af57e540e721d4f4ebd

**Comment by Thaodan** [comment]
fixed by https://github.com/hughsie/fwupd/commit/156538f1c396e68586c17af57e540e721d4f4ebd
