### ISSUE TITLE
Unable to see daemon debugging output from a snap autoinstaller

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#1124]
Currently launching a snap autoinstaller based archive the `--verbose` flag only gets carried over to the client since the daemon starts from dbus activation.

I was thinking about this, and had an idea that may _generally_ help debugging.

What if when the client connects to the daemon offer an option that will adjust daemon verbosity at that time?  So if the client is launched with `--verbose` the daemon switches to `--verbose` at that time too?

The other option is to modify snap auto installer to also modify the systemd unit to add `--verbose` when the auto installer is launched with verbose.

**Comment by hughsie** [comment]
Hmm, lots to think about there. I assume the daemon would just start dumping stuff to the journal rather than proxy it back to the client. The tricky bit is working out how to "unset" the --verbose flag when the daemon has quit.

**Comment by superm1** [comment]
Yes dumping to the journal was my expectation.  But when someone has a problem, you tell them to do something along these lines to get you the debugging:

# systemctl stop fwupd
# fwupdmgr action --verbose
# journalctl -u fwupd.service

> The tricky bit is working out how to "unset" the --verbose flag when the daemon has quit.

You mean when the _client_ has quit right?

**Comment by hughsie** [comment]
I'm a bit hesitant allowing users to magically cause a daemon running as root to dump loads of stuff in the journal -- it seems like it's a privileged operation to see the inner workings of the daemon.

**Comment by superm1** [comment]
That's true.  What about if this behavior only happened when the client was launched with `sudo` via a PK check?  Similar to how we only show serial number when the client was run with permissions.

**Comment by hughsie** [comment]
> when the client was launched with sudo

I think that's a really good idea.

**Comment by hughsie** [comment]
Good to close now?
