### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by Batarian711** [hughsie/fwupd#1137]
I want to design a custom logo for you. For the readme file. What do you say?

**Comment by hughsie** [comment]
We've kinda got one: https://github.com/hughsie/fwupd/blob/master/data/org.freedesktop.fwupd.svg although other ideas certainly very welcome.

**Comment by Batarian711** [comment]
Inspired by the old logo, I designed a logo that resembles a minimalist old logo and contains the letter F in small detail. What dou you think?
![FW](https://user-images.githubusercontent.com/41051393/55664242-ecbe9480-5833-11e9-9ce4-5d4743ba95df.jpg)

**Comment by hughsie** [comment]
Thanks for that, but I really prefer the current logo. Sorry.
