### ISSUE TITLE
Having automatic clean up for /boot/efi/EFI/debian/fw/

### ISSUE THREAD

**Issue by timevortex** [hughsie/fwupd#1216]
Hi there,

Just creating this issue to talk about if it makes sense to have some kind of internal mechanism in fwupdmgr that cleans up after itself in /boot/efi/EFI/debian/fw/.

When a firmware update is failing and fwupdmgr is continually used to attempt to apply the update, this partition is getting filled up with lots of .cap files until there is no more space left in /boot. Of course this can be manually cleaned up but I think it makes sense that fwupdmgr handle the garbage collection here since it's responsible for creating these files (at least that's my understanding).

Thoughts?

Cheers,
Parth
PS: I had a quick look with version 0.8.2-2 and I didn't see this happening either automatically (or being able to do so via some 'clean' sub-command). If something like this functionality was added in a later version of fwupdmgr please let me know and I'll try with that!

**Comment by hughsie** [comment]
We added this in 1.0.6 which was released over a year ago. Debian is going to have to update fwupd soon, the 0.8.x branch doesn't even get security updates...
