### ISSUE TITLE
Snap version fails: '/snap/fwupd/880/bin/fwupdmgr: not found'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hughsie/fwupd#1281]
To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
fwupdmgr --version
/snap/fwupd/880/fwupd-command: 41: exec: /snap/fwupd/880/bin/fwupdmgr: not found
```

Note, the switch `--version` is only present since version 0.9.6. If you use an
earlier version, please use the package manager to find out the package
version. For example, `dpkg -l fwupd`.

```
$  dpkg -l fwupd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-=============================================
ii  fwupd                1.0.9-0ubuntu2  amd64           Firmware update daemon
```

```shell
$ fwupdmgr get-devices
/snap/fwupd/880/fwupd-command: 41: exec: /snap/fwupd/880/bin/fwupdmgr: not found
```

Please answer the following questions:

- Operating system and version: Linux Mint 19.2 Cinnamon
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): snap
- Have you tried rebooting? yes
- Are you using an NVMe disk? yes
- Is secure boot enabled (only for the UEFI plugin)? no

The snap version of fwupd, which was failing to unmount at shutdown, showed a problem when i ran 'snap list'. So I used 'snap remove' to remove it and then I reinstalled it with `snap install fwupd --classic`. And now when I try to use the program it reports:

`/snap/fwupd/880/fwupd-command: 41: exec: /snap/fwupd/880/bin/fwupdmgr: not found`

There is also this report from systemd:

```
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION                             
● snap-core-7270.mount     loaded failed failed Mount unit for core, revision 7270      
● snap-core-7396.mount     loaded failed failed Mount unit for core, revision 7396      
● snap.fwupd.fwupd.service loaded failed failed Service for snap application fwupd.fwupd
```

I find that immediately after reinstalling the snap, I can install firmware updates - but, after that, I end up in the present situation. EDIT: actually, no; now it is more broken than that. Witness the following.
```

$  snap list
Name               Version          Rev   Tracking  Publisher       Notes
core                                7396  stable    canonical✓      broken
core18             20190723         1074  stable    canonical✓      base
fwupd              1.2.10           880   stable    richard-hughes  classic
gtk-common-themes  0.1-22-gab0a26b  1313  stable    canonical✓      -
keepassxc          2.4.3            378   stable    keepassxreboot  -
 ~  $  snap remove fwupd
fwupd removed
 ~  $  sudo rm -fr /usr/local/bin/fwupd
[sudo] password for nicholas: 
 ~  $  sudo snap install fwupd --classic
fwupd 1.2.10 from Richard Hughes installed
 ~  $  fwupdmgr get-updates
/snap/fwupd/880/fwupd-command: 36: /snap/fwupd/880/fwupd-command: /snap/fwupd/880/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: not found
/snap/fwupd/880/fwupd-command: 41: exec: /snap/fwupd/880/bin/fwupdmgr: not found
```

Perhaps the `rm -fr /usr/local/bin/fwupd` was a mistake. But (1) I wished to remove remnants of any (`apt`) installation and (2) I thought snaps were self-contained? But, ah, I've just noticed that `snap list` says the 'core' is broken. I will try reinstalling that. Hmm:

```
$  snap install core
2019-08-12T21:58:18+01:00 INFO Waiting for restart...
core 16-2.40 from Canonical✓ installed
 ~  $  fwupdmgr get-updates
Unsupported daemon version 1.0.9, client version is 1.2.10
```

**Comment by superm1** [comment]
If you want to remove your apt based install it should be:
`# apt remove fwupd`

Snaps are self-contained but there are 2-3 files that are shared with the snap and deb regarding policykit policies.  So these can stomp on each other.

```
core 16-2.40 from Canonical✓ installed
 ~  $  fwupdmgr get-updates
Unsupported daemon version 1.0.9, client version is 1.2.10
```

It's using the deb provided client (`/usr/bin/fwupdgmr`) to contact the snap provided server.

```
 ~  $  fwupdmgr get-updates
/snap/fwupd/880/fwupd-command: 36: /snap/fwupd/880/fwupd-command: /snap/fwupd/880/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: not found
/snap/fwupd/880/fwupd-command: 41: exec: /snap/fwupd/880/bin/fwupdmgr: not found
```

Something weird is going on.  can you try to remove `~/snap/fwupd` and `/root/snap/fwupd` directories and try again?

**Comment by LinuxOnTheDesktop** [comment]
> If you want to remove your apt based install it should be [. . .]

I should have said: yes, I did that first. I used that `rm` in addition to `apt remove` in order to avoid precisely the sort of problems that seem to have come up anyway, viz., residues from the old apt installation. I imagine that using apt to _fully_ remove the old package - by doing `apt purge fwupd` - would have removed `~/snap/fwupd`; would it have removed also `/root/snap/fwupd'? If not, then perhaps the snap version of the software should be alive to the possibility of the latter stuff existing.

Anyhow, having now run the commands you recommended - and having removed all my snaps and reinstalled them - the snap version of `fwupdmgr` seems fine (though I remain confused about the relation between `fwupdmgr` and `fwupd`).

I will close this bug report if you think there's is nothing to do at your end.

**Comment by superm1** [comment]
>  imagine that using apt to fully remove the old package - by doing apt purge fwupd - would have removed ~/snap/fwupd

Removing via apt doesn't touch `/root/snap` or `~/snap`.  those are only used via snap package.

>If not, then perhaps the snap version of the software should be alive to the possibility of the latter stuff existing.

Completely agree, there is some problem that occurred with junk in one of those directories leading to the problematic behavior you encountered.



>Anyhow, having now run the commands you recommended - and having removed all my snaps and reinstalled them - the snap version of fwupdmgr seems fine (though I remain confused about the relation between fwupdmgr and fwupd).

```
/snap/fwupd/880/fwupd-command: 36: /snap/fwupd/880/fwupd-command: /snap/fwupd/880/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: not found
```


Do you have any idea what version of the snap you upgraded from?  It would be good to try to reproduce this to find where the problem actually was.  If you don't have that information then I think we should close that and re-open if someone else encounters and we want to debug further.

**Comment by LinuxOnTheDesktop** [comment]
> Do you have any idea what version of the snap you upgraded from? 

I am afraid not. If the snap upgraded itself then it did so automatically (in a way that is meant to just work . . :).

**Comment by superm1** [comment]
Yeah it's _supposed_ to "just work".    Something is wrong with this script that's part of the snap I think.
https://github.com/hughsie/fwupd/blob/master/contrib/snap/fwupd-command

**Comment by superm1** [comment]
If someone encounters this again in the future, please re-open.  It would be good to examine the state of ~/snap and /root/snap at that time.
