### ISSUE TITLE
fwupd.spec isn't built by meson/ninja

### ISSUE THREAD

**Issue by vathpela** [hughsie/fwupd#134]
fwupd.spec should probably get built as part of the normal build process, rather than with external tooling.

**Comment by hughsie** [comment]
I think we need to do the substitution in the Travis script, rather than meson, otherwise it makes the end product non-reproducible.

**Comment by superm1** [comment]
Meson does have an [RPM module](http://mesonbuild.com/RPM-module.html), but it isn't meant for programmatic use.  It just creates the initial template with the list of the dependencies and requires someone to go fill in the rest.

As @hughsie said, by the CI being run now on both Fedora and Debian packaging any time that either need changing to the point that a build fails to build or fails to install packages it should be caught immediately.
