### ISSUE TITLE
Bug v0.9.3 /usr/lib/fwupd/remotes.d: No such file or directory

### ISSUE THREAD

**Issue by PieterDeBruijn** [hughsie/fwupd#137]
3 users (and me) have this error.
I’m getting an error when running `fwupdmgr refresh` in the v0.9.3 release:
Error opening directory “/usr/lib/fwupd/remotes.d”: No such file or directory

More info:
https://aur.archlinux.org/packages/fwupd/

**Comment by hughsie** [comment]
So, I'm guessing /usr/lib/fwupd exists but not /usr/lib/fwupd/remotes.d ? Did the arch build perhaps create the former and not the latter?

**Comment by PieterDeBruijn** [comment]
Correct. Manually adding the dir, fixes the error:
sudo mkdir /usr/lib/fwupd/remotes.d
and refresh runs without issues. This can be fixed (best) in the Arch build script? Then I'll report back downstream.

**Comment by hughsie** [comment]
You can either create the directory in the pkgbuild, or backport that last patch, which ever is easiest.

**Comment by ArchangeGabriel** [comment]
What is this directory used for? Should it be created by the package even with the patch?

**Comment by superm1** [comment]
It's for allowing packages to ship additional remote locations.  I think it makes sense to have it created directly by meson (or meson_post_install.sh).  Patches welcome!
