### ISSUE TITLE
Logitech Unifying devices VID & PID should not be prefixed by USB

### ISSUE THREAD

**Issue by xnlcasad** [hughsie/fwupd#144]
Unifying PIDs are not USB PIDs. Moreover there can be collisions as they are in different namespaces.

To generate the uuid we should use something different from USB\VID_XXXX&PID_XXXX. I suggest using UFY\VID_XXXX&PID_XXXX where PID_XXXX is the Unifying ID of the device.

**Comment by hughsie** [comment]
Fu  using 493e056b-f984-5469-a309-c8c035ebc55d for UFY\VID_046D&PID_4027
