### ISSUE TITLE
"FakeDevice" Integrated Webcam shows up on real systems

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#145]
I was just running a git build (that I self generated from CI packaging scripts) and noticed that the _FakeDevice_ is showing up on real `fwupdmgr get-devices` output.

I am thinking by default the 'test' plugin shouldn't be installed.

**Comment by hughsie** [comment]
We need the test plugin for the CI otherwise there's nothing to test.

**Comment by superm1** [comment]
Right, but I mean perhaps it shouldn't be stroed into the debs and rpms, but just copied into the docker filesystem during test.

**Comment by ArchangeGabriel** [comment]
Is it this thing:
```
  Guid:                 9bab7d9d-9396-5929-bd36-64ff7bc84804
  Guid:                 31f4c6bf-8c1e-5c88-8153-984cbe1dad0e
  DeviceID:             usb:00:07
  Plugin:               usb
  Flags:                none
  Version:              153.6
  Created:              2017-06-19
```
?

By the way, I seem to remember having a device name above that, but it apparently does not show anymore…

**Comment by ArchangeGabriel** [comment]
Hum, wrote too fast, guid does not match https://github.com/hughsie/fwupd/blob/master/plugins/test/fu-plugin-test.c.

**Comment by superm1** [comment]
No, that's a real device.  This is the FakeDevice: https://github.com/hughsie/fwupd/blob/81f96797f6a4d5d48124d871ec441e177a7ec597/plugins/test/fu-plugin-test.c#L57

**Comment by superm1** [comment]
Another idea rather than not installing into real filesystems, maybe only initialize the test plugin if something is in the environment when fwupd is spawned and set that up in the CI environment?

**Comment by hughsie** [comment]
I actually set the CI=true environment var in the travis builds, so I guess we could self-disable if that env var isn't set?

**Comment by superm1** [comment]
Might need some hokey way to pass that into the d-bus spawned fwupd (not sure if env variables will carry).  Otherwise that sounds good.

**Comment by hughsie** [comment]
Ahh yes, right. That was exactly the reason I shifted away from the env var; it was tricky to "inject" it into the spawned DBus activated process.

**Comment by superm1** [comment]
Something like this (untested):

```
diff --git a/contrib/ci/build_and_install_debs.sh b/contrib/ci/build_and_install_debs.sh
index faba5a3..4c98ce5 100755
--- a/contrib/ci/build_and_install_debs.sh
+++ b/contrib/ci/build_and_install_debs.sh
@@ -14,5 +14,8 @@ dpkg-buildpackage
 dpkg -i ../*.deb
 
 # run the installed tests
-/etc/init.d/dbus start
-gnome-desktop-testing-runner fwupd
+if [ "$CI" = "true" ]; then
+       sed "s,Exec=,Exec=CI=$CI ," /usr/share/dbus-1/system-services/org.freedesktop.fwupd.service
+       /etc/init.d/dbus start
+       gnome-desktop-testing-runner fwupd
+fi
```

**Comment by superm1** [comment]
I've got a PR that will do this open here now: https://github.com/hughsie/fwupd/pull/148

**Comment by superm1** [comment]
Closed with https://github.com/hughsie/fwupd/commit/f3f4390155f4768dd4c5b9664877397f0a60607c
