### ISSUE TITLE
`fwupd: report 0x00 unknown length` logged per keypress

### ISSUE THREAD

**Issue by da2x** [hughsie/fwupd#151]
I’ve got a wired Logitech G810 keyboard (Nordic layout).

The following message is repeated once per keydown and once per keyup event.

    fwupd: report 0x00 unknown length

Why is fwupd involved every time I press a key on my keyboard? That seems excessive for a little helper program designed to take care of my firmware update needs.

This keyboard doesn’t use the Logitech Unifying dongle, as it has got it’s own wired USB interface.

[Verbose lsusb output](https://gist.github.com/da2x/a9dc0c2de085179e8dae6d452334d784) for this device.

fwupd-0.9.4-1.fc26.x86_64

**Comment by hughsie** [comment]
Can you try the recently released 0.9.5 please? I've rewritten a chunk of the notification handling code. Thanks!

**Comment by sentabi** [comment]
I've similiar issue
```
Jul 07 11:03:19 situal fwupd[7598]: report 0x02 unknown length
Jul 07 11:03:19 situal fwupd[7598]: report 0x20 unknown length
Jul 07 11:03:24 situal fwupd[7598]: report 0x02 unknown length
Jul 07 11:03:24 situal fwupd[7598]: report 0x02 unknown length
Jul 07 11:03:24 situal fwupd[7598]: report 0x20 unknown length
```
it's generate tons of these log 

Other logs
```
Jul 07 11:04:27 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:13] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Jul 07 11:04:27 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:15] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Jul 07 11:04:27 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:13] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Jul 07 11:04:27 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:15] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Jul 07 11:04:31 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:13] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Jul 07 11:04:31 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:15] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Jul 07 11:04:45 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:13] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Jul 07 11:04:45 situal systemd[1]: [/usr/lib/systemd/system/fwupd.service:15] Unknown lvalue 'ProtectKernelModules' in section 'Service'
```
using latest version 
```
fwupd-0.9.5-1.fc25.x86_64
```

**Comment by hughsie** [comment]
> Jul 07 11:03:19 situal fwupd[7598]: report 0x02 unknown length

These are not in the HID++ specification... I guess we just need to ignore them.

> Unknown lvalue 'ProtectKernelModules' in section 'Service'

Harmless, if you update systemd the warning will go away.
