### ISSUE TITLE
T400 middle click

### ISSUE THREAD

**Issue by uacode** [hughsie/fwupd#160]
Hello,

I has received updates from gnome market.
After this update mouse lost middle click.

How I can fix middle click? On Windows and official software reconfig does not helps.

Thank you!

**Comment by hughsie** [comment]
The only thing the update fixed was to remove the vulnerabilities associated with the MouseJack issue, I've not heard of any other side effects from anybody else. Make sure you remove, insert the receiver, and maybe unpair and pair the device with Solaar and then hopefully it should work again.
