### ISSUE TITLE
Circular deps in spec file

### ISSUE THREAD

**Issue by xsuchy** [hughsie/fwupd#20]
Why is there:
```
BuildRequires: fwupdate-devel
```
in spec file?

fwupdate-devel is subpackage of fwupdate, so for building fwupdate you need its subpackage. This is circular dependency.

**Comment by xsuchy** [comment]
Ah, scratch this, fwupdate-devel != fwupd-devel.

**Comment by jared-dominguez** [comment]
You filed this against fwupd, which is an entirely different package 
from fwupdate. fwupdate's build dependencies look fine.
