### ISSUE TITLE
fwupdmgr can't pull updates automatically

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#24]
Currently fwupdmgr has all the data it needs to be able to download an update from Appstream data, but it can't do the download itself.  When running from gnome-software, this isn't a big deal because gnome-software will download for you and pass to fwupd.  When running fwupdmgr on the command line you have to manually wget/curl the file in advance and then call the appropriate installation argument.

For a full command line experience you should be able to have fwupdmgr parse the appstream data, fetch the file and apply the update.

**Comment by hughsie** [comment]
I think I've done this with 777917ef215913f43f5c9f795d3be4842ba970d9 -- please tell me if it works for you. Thanks!
