### ISSUE TITLE
Cannot update Logitech Unifying Receiver (version of org.freedesktop.fwupd incorrect: failed predicate [0.9.2 ge 0.8.1])

### ISSUE THREAD

**Issue by Prinzhorn** [hughsie/fwupd#253]
No sure if there is something wrong with my system or if that's a bug in fwupd. I hope somebody can help me install the update. Ubuntu 17.04.

```
$ sudo fwupdmgr update
Downloading RQR12.07_B0029 for Unifying [runtime]...
Updating RQR12.07_B0029 on Unifying [runtime]...
Decompressing…         
version of org.freedesktop.fwupd incorrect: failed predicate [0.9.2 ge 0.8.1]
```

![selection_121](https://user-images.githubusercontent.com/679144/30431671-a5bd1316-995f-11e7-84d4-545bcad032aa.png)

**Comment by hughsie** [comment]
You need fwupd at least version 0.9.2 to apply the update.

**Comment by Prinzhorn** [comment]
Thank you very much for the quick answer. That means I either need to find a ppa or compile it myself, right?

**Comment by Piskvor** [comment]
@Prinzhorn: Found no PPAs, compiling is a yak-shaving chain of dependencies. What worked for me was this: get a bootable USB disk with a distro containing a current version (I went with [Xubuntu 17.10 b1](http://cdimage.ubuntu.com/xubuntu/releases/artful/beta-1/), which has 0.9.7. Note that you probably want a 64-bit version of the OS - 32-bit fwupdate segfaults if device is plugged in.

- Boot the live distro
- plug in the receiver
- `apt update`
- `apt install fwupd`
- edit /etc/fwupd/remotes.d/lvfs-testing.conf - change `Enabled=false` to `Enabled=true`
- `fwupdmgr refresh && fwupdmgr update`

**Comment by superm1** [comment]
@Piskvor 32 bit fwupd is segfaulting when a device is plugged in for you?  I think we should fix that.  Would you mind to file a separate issue with the details for this?

**Comment by Prinzhorn** [comment]
@Piskvor thank you very much. I just did the upgrade as you've described, even though I already updated it on AskUbuntu some time ago https://askubuntu.com/questions/955177/cannot-update-logitech-unifying-receiver-version-of-org-freedesktop-fwupd-incor
