### ISSUE TITLE
We should have a i686 CI target

### ISSUE THREAD

**Issue by hughsie** [hughsie/fwupd#273]
I don't mind if this is Debian or Fedora, although the latter (along with CentOS) seems to have deprecated i686 builds. We had a crasher bug in the past on i386 so I guess it's worth testing.

**Comment by superm1** [comment]
Do you think it needs to be a full test suite run?  Or Just a compile test?

**Comment by superm1** [comment]
And furthermore full "installed" test suite, or just local test suite?

**Comment by hughsie** [comment]
I've prefer the whole installed shebang, the bug last time was a runtime crash, not a compile failure.

**Comment by superm1** [comment]
OK.  So then I guess the question is repurpose one of the existing tests to do it's run as 32 bit, or introduce another  test.  Another test will increase the time of every CI run by 5-10 minutes, repurposing an existing one shouldn't change anything.

Ubuntu has also deprecated 32 bit too, so it's probably better to put this in one of the Debian builds.

**Comment by hughsie** [comment]
I think another target is fine; we could argue that Debian could just be converted to 32 bit builder, but debian x64 is kinda an important target too. I'm not normally waiting on builds unless it's release time but either would be fine. We could even disable the arch one by default, although I'm not sure that helps much.
