### ISSUE TITLE
man page syntax ambiguities

### ISSUE THREAD

**Issue by gaenserich** [hughsie/fwupd#285]
The man page for `fwupdmgr` contains some syntactical omissions that leave certain usages ambiguous, e.g. under the `Commands` heading:
```shell
COMMANDS
       This program takes commands with a variable number of arguments.

                 get-details
              Gets details about a firmware file.
```
Convention typically holds that if a parameter expects another parameter after it, the man page should include a placeholder in all caps after it, e.g.:
```shell
                 get-details FILE
              Gets details about a firmware file.
```
The omission is specifically detrimental on something like
```shell
                 install
              Install a firmware file on this hardware.
```
Which hardware? All of the attached hardware, or a specific component? If the latter, do I use a GUID or the DeviceId as reported by `fwupdmgr get-devices`? A placeholder like GUID or DEVICEID would definitely resolve this.

**Comment by hughsie** [comment]
So, in general I'm not very good at this kind of documentation. I'll have a look if it's going to be easier to just generate them at build time.
