### ISSUE TITLE
`fwupdmgr --version` doesn’t work

### ISSUE THREAD

**Issue by paulmenzel** [hughsie/fwupd#300]
The GitHub issue template requests the output of `fwupdmgr --version`, but that is not available in fwupd 0.7.0-0ubuntu4.3 shipped with Ubuntu 16.04.3 LTS.

**Comment by hughsie** [comment]
`--version` was added in fwupd 0.9.6, so much newer than you have there.

**Comment by superm1** [comment]
I don't think it's worth backporting --version to 0_7_x for this purpose, let's just update the template to refer to alternately looking at your package manager for the information.

**Comment by hughsie** [comment]
WFM.

**Comment by paulmenzel** [comment]
I’ll do that then.
