### ISSUE TITLE
Remove docbook package dependencies

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#313]
Some conversion was done in https://github.com/hughsie/fwupd/commit/3b847537693b8659feb039e94c06d5b953b80b42#commitcomment-25567067 to use `help2man `instead but it's not yet complete.

Notable changes still needed:

- dfu-tool.sgml needs converting
- docbook dependencies need removing
- arch PKGBUILD needs to be updated

**Comment by superm1** [comment]
1b907a7d253c96d2e5b03ad9bb8c4040a39d9060

**Comment by ArchangeGabriel** [comment]
Thanks!
