### ISSUE TITLE
fwupd seems to be listing the firmware updates backwards

### ISSUE THREAD

**Issue by hughsie** [hughsie/fwupd#319]
See https://bugzilla.redhat.com/show_bug.cgi?id=1506609

    alessio@pbale ~> fwupdmgr get-updates
    XPS 13 9360 System Firmware has firmware updates:
    GUID:                    5ffdbc0d-f340-441c-a803-8439c8c0ae10
    ID:                      com.dell.uefi5ffdbc0d.firmware
    Update Version:          0.2.1.0
    Update Remote ID:        lvfs
    Update Checksum:         SHA1(cef6088e1104941d8ed009d27140c47b5903b13c)
    Update Location:         https://fwupd.org/downloads/06d4df9ec3817be64a0d4b55927a687ab0e2cb66-firmware_XPS_9360_2_1_0.cab
    ID:                      com.dell.uefi5ffdbc0d.firmware
    Update Version:          0.2.2.1
    Update Remote ID:        lvfs
    Update Checksum:         SHA1(52b875e4eab8bf4c384861b9cd878c62e8fc899f)
    Update Location:         https://fwupd.org/downloads/4efcda1e3a49b1a82121dc155d73703bcec05e31-firmware_XPS_9360_2_2_1.cab
    ID:                      com.dell.uefi5ffdbc0d.firmware
    Update Version:          0.2.3.1
    Update Remote ID:        lvfs
    Update Checksum:         SHA1(18d9501fc82e8c39acb57693e2c6ad60a2712f9a)
    Update Location:         https://fwupd.org/downloads/6fd391badc79a4d9a2c9916073f6941f885a22fd-firmware_XPS_9360_2_3_1.cab

**Comment by superm1** [comment]
Also it seemed like it was stepping through them one version at a time rather than right to newest.  I guess that's related since the "first" is being picked.
