### ISSUE TITLE
Logitech K780 Firmware Update Fails

### ISSUE THREAD

**Issue by KennyStier61** [hughsie/fwupd#352]
(First filed to Launchpad: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1740889)

I initially tried to update the firmware of my Logitech K780 Wireless Keyboard via Gnome Software, and it acted like it was pushing the update, but then threw an error.

"Unable to update "Logitech K780 Multi-Device Wireless Keyboard" failed to write @0x10260: failed to get event after timeout"

So I turned my keyboard (which still wasn't working after the update failed and the LED was flashing green and red) off and back on and tried the update again. Only this time, it threw a different error. "no method to detach"

It did the same thing when running the fwupdmgr update command.

# Apport Data

ProblemType: Bug
DistroRelease: Ubuntu 17.10
Package: fwupd 0.9.7-2
ProcVersionSignature: Ubuntu 4.13.0-21.24-generic 4.13.13
Uname: Linux 4.13.0-21-generic x86_64
ApportVersion: 2.20.7-0ubuntu3.6
Architecture: amd64
CurrentDesktop: ubuntu:GNOME
Date: Tue Jan 2 10:20:20 2018
InstallationDate: Installed on 2017-12-28 (4 days ago)
InstallationMedia: Ubuntu 17.10 "Artful Aardvark" - Alpha amd64 (20170926)
ProcEnviron:
 TERM=xterm-256color
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/usr/bin/fish
SourcePackage: fwupd
UpgradeStatus: No upgrade log present (probably fresh install)
# Logs, Screenshots, Etc.
[Screenshots and Video of Keyboard during update](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1740889/+attachment/5030163/+files/fwupd-bug-media.tar.gz)
[Dependencies.txt](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1740889/+attachment/5030164/+files/Dependencies.txt)
[JournalErrors.txt](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1740889/+attachment/5030165/+files/JournalErrors.txt)
[ProcCpuinfoMinimal.txt](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1740889/+attachment/5030166/+files/ProcCpuinfoMinimal.txt)

# Requested Info

```shell
$ fwupdmgr --version
client version:	0.9.7
daemon version:	0.9.7
compile-time dependency versions
	appstream-glib:	0.7.1
	gusb:	0.2.11
```
```shell
$ fwupdmgr get-devices
Intel AMT (unprovisioned)
  DeviceID:             /dev/mei
  Guid:                 2800f812-b7b4-2d4b-aca8-46e0ff65814c
  Plugin:               amt
  Flags:                internal|registered
  Version:              7.1.70
  VersionBootloader:    7.1.70
  Created:              2018-01-02

Unifying Device. Wireless PID:405b
  DeviceID:             /sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.7/2-1.7:1.2/0003:046D:C52B.0003/0003:046D:405B.0004/hidraw/hidraw2
  Guid:                 3932ba15-2bbe-5bbb-817e-6c74e7088509
  Description:          <p>The K780 is a keyboard that allows switching among three paired hosts.</p>
  Plugin:               unifying
  Flags:                updatable|supported|registered
  DeviceVendor:         Logitech
  DeviceVendorId:       USB:0x046D
  Version:              MPK01.00_B0018
  VersionBootloader:    BOT25.00_B0005
  Created:              2018-01-02

Unifying Receiver
  DeviceID:             /sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.7
  Guid:                 77d843f7-682c-57e8-8e29-584f5b4f52a1
  Guid:                 9d131a0c-a606-580f-8eda-80587250b8d6
  Plugin:               unifying
  Flags:                updatable|supported|registered
  DeviceVendor:         Logitech
  DeviceVendorId:       USB:0x046D
  Version:              RQR12.07_B0029
  VersionBootloader:    BOT01.02_B0015
  Created:              2018-01-02

USB Receiver
  DeviceID:             usb:00:01:07
  Guid:                 77d843f7-682c-57e8-8e29-584f5b4f52a1
  Guid:                 39a2d8d5-9394-5e6a-b7fc-6fcebfe777aa
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x046D
  Version:              18.7
  Created:              2018-01-02

2nd Generation Core Processor Family Integrated Graphics Controller
  DeviceID:             ro__sys_devices_pci0000_00_0000_00_02_0
  Guid:                 857bfd21-08b6-5b07-968c-40f636e5e019
  Plugin:               udev
  Flags:                internal|registered
  DeviceVendor:         Intel Corporation
  DeviceVendorId:       PCI:0x8086
  Created:              2018-01-02

Yubikey NEO OTP+U2F+CCID
  DeviceID:             usb:00:01:03
  Guid:                 7e9ede09-680a-55f2-b234-8c9a70de248d
  Guid:                 2f598c6e-e41f-595c-b872-7713f6105d1a
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x1050
  Version:              3.67
  Created:              2018-01-02

```

- Operating system and version: Ubuntu 17.10
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): How it came in the ISO/apt 
- Have you tried rebooting? No
- Are you using an NVMe disk? No
- Is secure boot enabled (only for the UEFI plugin)? No

**Comment by SonicFrog** [comment]
First, have you tried the latest git master version?

If that doesn't fix it would you mind running the daemon in verbose mode (something along the lines of /usr/libexec/fwupd/fwupd -v) and posting the log somewhere?

**Comment by superm1** [comment]
I just committed b0398b00cfb5be53610b1ef289c9d0365994e076 which will make building git master on Ubuntu 17.10 easier.
Follow the directions here: https://github.com/hughsie/fwupd/tree/master/contrib for building deb packages of master on Ubuntu 17.10 with docker.

**Comment by superm1** [comment]
@DirtySoc thanks for your confirmation.  @SonicFrog this means that fwupd 1.0.6 (which is in Ubuntu 18.04) is still affected.  Would you be able to help look at this and comment?

**Comment by teleyinex** [comment]
Just tried it today, and it failed as well. I'm on Ubuntu 18.04. I'd to turn off/on again the keyboard to get it working.

**Comment by hughsie** [comment]
@teleyinex -- Can you try with fwupd 1.1.2 please -- we rewrote and improved the unifying plugin and it now seems to work a lot better for more people. My keyboard update works flawlessly every time now.

**Comment by superm1** [comment]
I'm closing older bugs with `needsinfo` tags such as this one.  Can you please retry with a current release (1.1.3) and if the issues continue to exist, please re-open.

Even if the current release is not yet packaged for your distro, you can install it via snap like this:
```
# snap install --classic fwupd
```
