### ISSUE TITLE
Allow to build without gusb

### ISSUE THREAD

**Issue by paulmenzel** [hughsie/fwupd#371]
Trying to build fwupd 1.0.3 to update Dell workstations, it looks like I am unable to disable the gusb dependency. Did I overlook something? If not, could it be made configurable?

**Comment by hughsie** [comment]
GUsb is a core dep, it's used pretty much everywhere -- is there a reason you need to compile without it?

**Comment by paulmenzel** [comment]
On 01/17/18 12:55, Richard Hughes wrote:
> GUsb is a core dep, it's used pretty much everywhere -- is there a reason you need to compile without it?

The only reason is, that we won’t use it, and try to keep what we 
compile minimal.

**Comment by hughsie** [comment]
GUsb is a core dep, sorry. It's a ABI stable, *tiny* .so wrapping libusb, there's really not much justification not building it. Sorry.

**Comment by paulmenzel** [comment]
Fair enough. I still think, I’d be good practice to be able to disable unwanted components/parts. Thank you for your replies nevertheless.
