### ISSUE TITLE
Question regarding fwupdate --esp-path

### ISSUE THREAD

**Issue by ArchangeGabriel** [hughsie/fwupd#421]
This was introduced in `fwupdate` so that Arch users can finally have this working without compiling from source, but what I’m not sure of is when should this option be passed as arg? For `fwupdmgr update`? Or are users currently required to run `fwupdate` directly?

**Comment by superm1** [comment]
Let me see if I understand correctly.  Normally with `fwupdate` 10+ you would set an argument on command line that would override the path.  You're wondering how `fwup_set_esp_mountpoint `gets called from fwupd?

I suppose it's a bit of a shift to allow setting this path at runtime that fwupd didn't comprehend yet.
My gut would say we should add this as a conf option to a new `uefi.conf` in `/etc/fwupd/`, although that might not really be necessary anymore after a fix for https://github.com/rhboot/fwupdate/issues/97 is developed.

@hughsie your thoughts on the matter?

**Comment by superm1** [comment]
Yeah you're probably right it will take some time so it's worthwhile to let fwupd override it.  Unless @hughsie thinks it's the wrong approach i'll work on a PR for it soon.

https://github.com/rhboot/fwupdate/blob/master/linux/fwupdate.c#L234

**Comment by superm1** [comment]
Submitted a PR above that should offer this via conffile.  if that's accepted I'd say you should backport that to your fwupd package.

**Comment by ArchangeGabriel** [comment]
Thanks, I’m backporting that.

**Comment by ArchangeGabriel** [comment]
Done, as well as wiki update: https://wiki.archlinux.org/index.php/Fwupd#Running_fwupd

**Comment by daenney** [comment]
@ArchangeGabriel I don't really understand the instructions on the Arch wiki. It suggests that if the ESP is not mounted at `/boot/EFI`, you need to set `OverrideESPMountPoint` to `esp`? Or the actual path to the ESP, i.e `/boot`?

Given that Arch seems to use systemd-bootd by default, and the [wiki recommends mounting the ESP on `/boot`](https://wiki.archlinux.org/index.php/systemd-boot#Installing_the_EFI_boot_loader), should the default on not be changed? The out-of-the-box experience is mildly broken now.

**Comment by ArchangeGabriel** [comment]
> Given that Arch seems to use systemd-bootd by default, and the wiki recommends mounting the ESP on /boot, should the default on Arch not be changed? The out-of-the-box experience is mildly broken now.

There is no such thing as a default bootloader in Arch. No-one is expected to use `systemd-bootd`, and GRUB is a better choice if you ask me because of `/boot` encryption.

**Comment by daenney** [comment]
Ah, you're indeed correct. In that case I suppose it doesn't matter much. Thanks!
