### ISSUE TITLE
Please add a build option to allow enabling/disabling of vapi/vala bindings

### ISSUE THREAD

**Issue by tgurr** [hughsie/fwupd#443]
appstream for example allows to configure this via -Dvapi=true/false. It would be nice to have this for fwupd as well so we are able to have the dependency on vapigen conditionally and not run into some kind of automagic.

**Comment by hughsie** [comment]
Could you write a PR for this please? Thanks.

**Comment by superm1** [comment]
I think this can be closed now.  Turning off introspection disables building these.

**Comment by superm1** [comment]
I'm going to close, if I turn out to be wrong, please re-open!
