### ISSUE TITLE
update logitech firmware to RQR12.08_B0030

### ISSUE THREAD

**Issue by arekm** [hughsie/fwupd#470]
Logitech windows software upgrades unifying receiver firmware to RQR12.08_B0030
while fwupd knows only about RQR12.07_B0029.

Please consider providing new version, too.

**Comment by arekm** [comment]
https://github.com/Logitech/fw_updates/tree/master/RQR12/RQR12.08

**Comment by arekm** [comment]
And 12.09 now:
https://github.com/Logitech/fw_updates/tree/master/RQR12/RQR12.09

**Comment by ktecho** [comment]
I'm interested in this as well, as I updated from RQR12.03_B0025 to RQR12.07_B0029 and now my mouse is left-clicking everything as fast as I click the button. I can't even select a text from a web page because it clicks a lot. Maybe latest firmwares fixes this...

**Comment by ktecho** [comment]
It seems like it was a hardware problem, so please forgot my last comment.

**Comment by hughsie** [comment]
>Can fwupd handle signed DFU

Yes! Can you try with 1.0.9 or preferably 1.1.2 -- the latter includes a much rewritten and improved unifying plugin and seems to work a lot better for more people.
