### ISSUE TITLE
Add "-r/--replace" to daemon commands

### ISSUE THREAD

**Issue by hadess** [hughsie/fwupd#475]
Would make it easier to test new versions.

**Comment by hughsie** [comment]
Makes sense; you got an example of this in another project?

**Comment by hadess** [comment]
upower? :)

**Comment by hughsie** [comment]
Isn't G_BUS_NAME_OWNER_FLAGS_REPLACE already set unconditionally? i.e. any new instance will "take over" from the old instance?

**Comment by hadess** [comment]
It does, indeed... Not sure what the problem was in my tests. Thanks for the quick answer.
