### ISSUE TITLE
Generic vector for firmware-based trojans

### ISSUE THREAD

**Issue by deepfire** [hughsie/fwupd#5]
In a twisted sense, this provides an easy-to-use, generic service for SMM[1] (and other firmware-based) trojans to install themselves.

It's an important day.  Great opportunities ahead.. 

--
1. See, for example, http://legbacore.com/Research_files/HowManyMillionBIOSWouldYouLikeToInfect_Full2.pdf

**Comment by hughsie** [comment]
By default fwupd should only be able to install signed capsules onto hardware.
