### ISSUE TITLE
Flatpak should have access to home or xdg download

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#555]
In my experience with testing the flatpak I was finding that it's awkward to install cab files (or flat blobs for that matter) since they need to go into `$HOME/.var/app/org.freedesktop.fwupd` to be recognized by sandbox confinement policies.

I think some better directories should be chosen by default and error messages clarified if not using appropriate directories for the sandbox.

Since the normal model is to download from LVFS manually and then install my two thoughts were either `--filesystem=xdg-download` or `--filesystem=home`.

And then also adjust the error message for file not found specifically if running in sandbox mode (maybe `-Daemon=false` is enough).

**Comment by hughsie** [comment]
Out of interest, how were you running fwupdtool from the flatpak bundle? I always just used sudo.

**Comment by hughsie** [comment]
Cut sure, good idea to have `--filesystem=xdg-download`

**Comment by superm1** [comment]
> I always just used sudo.

As I can tell that doesn't affect sandbox. I was trying with files in /tmp and unable to access them.
