### ISSUE TITLE
Need a way to run a command after last device in plugin is flashed

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#561]
A composite device that I'm working on a plugin for has a need to run a reboot command at the end of updating all devices if the last device isn't updated.

When all devices are being updated this is easily solved by install task ordering and putting the reboot command at the end of the last device, but if that device isn't being updated the reboot command still needs to be run.  The problem is the other devices won't know whether that last device is in the list of stuff to be updated.

I sort of feel like this needs to be a "plugin wide final install task" or something similar to that.  If it's done that way then the plugins `FuPluginData` can keep a boolean `needs->reboot`.

- Once one of the earlier devices is updated it can set `needs->reboot` to `TRUE`.
- If that last device is being updated it can set `needs->reboot` can be set to `FALSE`

So when the final install task ran if `needs->reboot` is `TRUE` the reboot command will be sent.

**Comment by superm1** [comment]
Maybe `update_cleanup` is sufficient though.

**Comment by hughsie** [comment]
> Maybe update_cleanup is sufficient though.

That's exactly what I was going to suggest.

**Comment by hughsie** [comment]
> it is called after every composite device rather than end of plugin

Ahh, so what's happening is:

    fu_engine_install_blob
      update(plugin, device)
      foreach plugin
        update_cleanup(plugin, device)
    fu_engine_install_blob
      update(plugin, device)
      foreach plugin
        update_cleanup(plugin, device)

And you need an update_cleanup() that runs after the whole PkInstallTask is done?

**Comment by superm1** [comment]
Yes exactly

**Comment by hughsie** [comment]
Got any good name ideas? I suppose it would be like a update_cleanup() that doesn't take a FuDevice. But then I guess it needs a list of FuDevices (or FuInstallTasks?) so it knows what was done...

**Comment by superm1** [comment]
How about this:

```fu_plugin_updates_finalize (GPtrArray *FuDevices, GError **error)```

Then pass in all the devices that were updated as that array.  That would be perfect.

**Comment by hughsie** [comment]
Args agreed. Perhaps `transaction_prepare()` and `transaction_cleanup()`?

**Comment by superm1** [comment]
Yeah, that's good.

**Comment by superm1** [comment]
I think you probably also need `FuPlugin *plugin` as the first argument

**Comment by hughsie** [comment]
I might have an hour to have a go at this now, modulo kids.
