### ISSUE TITLE
Firmware for Dell Latitude E7250

### ISSUE THREAD

**Issue by paulmenzel** [hughsie/fwupd#569]
On the Dell Latitude E7250, currently firmware A17 is installed. Currently, the update A19 is available on the [Dell support site][1].

Looking through the LVFS device list, there is only [Latitude E7250 MST Update][2]. And that has the version 3.10.001, which is different from A19.

`fwupdmgr get-devices` also only shows the Webcam, so I assume, that the LVFS device is a different device and the laptop here is not supported by the project. Is that true?

Is there a chance, that the device will be added to the LVFS list in the future, or does this only happen for new products?

[1]: https://www.dell.com/support/home/de/de/debsdt1/drivers/driversdetails?driverId=55JM5
[2]: https://fwupd.org/lvfs/device/92537619-b397-54cd-b4bf-ce5da9e0a61d

**Comment by superm1** [comment]
To me that sounds correct that it's not supported.
You would need to have a UEFI device showing up in the `get-devices` output for it to be updatable via UEFI in the first place.

The MST update is for a different device that's in there (the Synaptics MST controller).
