### ISSUE TITLE
Provide error when gcab is not found with 'meson build' building.

### ISSUE THREAD

**Issue by jeanlego** [hughsie/fwupd#574]
when doing meson build 
the build goes through until we hit 

src/meson.build:241:2: ERROR:  Unknown variable "colorhug_test_firmware".

gcab is not listed as a dependency making it criptic. 

Thanks for the great tool :)

**Comment by hughsie** [comment]
gcab really is a dependency, although we don't cope very well when libgcab-devel is installed and the command line tool isn't installed.

**Comment by superm1** [comment]
I've added an extra commit to check that the binary is there too.
