### ISSUE TITLE
no warning for missing depency before doing ninja build

### ISSUE THREAD

**Issue by jeanlego** [hughsie/fwupd#575]
when running ninja -C build install on fedora 28

we need
 
gtk-scan (form gtk-doc package)
/usr/lib/rpm/redhat/redhat-hardened-cc (from redhat-rpm-config)

**Comment by superm1** [comment]
I've added a PR for this to make meson fail if `gtk-scan` is missing.  What was the error for missing `/usr/lib/rpm/redhat/redhat-hardened-cc`?  If you can please share the `meson` output when it's not there that would be really helpful.
