### ISSUE TITLE
Feature request: blacklist function

### ISSUE THREAD

**Issue by CottonEaster** [hughsie/fwupd#617]
I have just read about a Lenovo firmware update stopping someone's machine from booting. (That update is not offered, not yet anyway, via fwupd, though other updates for the same computer are. But still.) So how about a blacklist function? One would not want accidentally - via the (blanket) `update` argument - to install such an update.

**Comment by superm1** [comment]
This is already supported.  You can blacklist plugins or devices in the conf file.
https://github.com/hughsie/fwupd/blob/master/data/daemon.conf#L9
