### ISSUE TITLE
Update not executed on Manjaro and Lenovo Thinkpad T470

### ISSUE THREAD

**Issue by ckoehn** [hughsie/fwupd#620]
As far as I can see the update is correctly scheduled but on boot it just displays:
```
Found update fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7-0
File \EFI\manjaro\fw\fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7.cap searched
Could not apply capsule update: Not found
fwupdate: Could not apply capsules: Not found
```
After this error message it continues with the normal boot order (manjaro).

```shell
$ fwupdmgr --version
client version:	1.1.0
daemon version:	1.1.0
compile-time dependency versions
	appstream-glib:	0.7.7
	gusb:	0.3.0
	efivar:	35
```

```shell
$ fwupdmgr get-devices
20HD000PUK System Firmware
  DeviceId:             888f97106c5be770592b21740d18c1d29aa8e1b9
  Guid:                 4e06f4ae-ab2e-4804-9a23-888e596a31e7
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.47
  VersionLowest:        0.1.23
  Icon:                 computer
  Created:              2018-08-05
  UpdateState:          success

UEFI Device Firmware
  DeviceId:             4718f2fc055b1c4de66633017326683a72592b4c
  Guid:                 bcff5fd8-0a99-48ad-b630-40e8eadb190e
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Version:              184.50.3425
  VersionLowest:        0.0.1
  Icon:                 audio-card
  Created:              2018-08-05

UEFI Device Firmware
  DeviceId:             efc88c8524a5d0ada629ba38b89ac722dc3d5efb
  Guid:                 4b37c365-ecb2-4d89-8e15-e93c27c6ce12
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Version:              0.1.31
  VersionLowest:        0.0.1
  Icon:                 audio-card
  Created:              2018-08-05
```

```shell
$ efibootmgr -v
BootNext: 0000
BootCurrent: 0001
Timeout: 2 seconds
BootOrder: 0001,0010,0011,0012,0013,0017,0018,0019,001A,001B,001C,001D,001E,001F,0024,0000
Boot0000* Linux Firmware Updater	HD(4,GPT,2307b9c5-536e-4c46-a31f-833eb8a3a0ac,0x800,0x96000)/File(\EFI\manjaro\fwupdx64.efi)
Boot0001* Manjaro	HD(4,GPT,2307b9c5-536e-4c46-a31f-833eb8a3a0ac,0x800,0x96000)/File(\EFI\Manjaro\grubx64.efi)
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0015  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0016  MEBx Hot Key	FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0017* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD1	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f601)
Boot001B* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001C* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001D* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001E  Other CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35406)
Boot001F  Other HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f606)
Boot0020* IDER BOOT CDROM	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,1)
Boot0021* IDER BOOT Floppy	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,0)
Boot0022* ATA HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0023* ATAPI CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)
Boot0024* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
```

```shell
$ efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7-0
```

```shell
$ tree /boot
/boot
├── efi
│   └── EFI
│       ├── boot
│       │   └── bootx64.efi
│       └── Manjaro
│           ├── fw
│           │   ├── fwupd-3b8c8162-188c-46a4-aec9-be43f1d65697.cap
│           │   └── fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7.cap
│           ├── fwupdx64.efi
│           └── grubx64.efi
├── grub
│   ├── ...
├── initramfs-4.14-x86_64-fallback.img
├── initramfs-4.14-x86_64.img
├── intel-ucode.img
├── linux414-x86_64.kver
├── memtest86+
│   └── memtest.bin
└── vmlinuz-4.14-x86_64

12 directories, 350 files
```

Please answer the following questions:
- Operating system and version: Manjaro
- How did you install fwupd: `pacman`
  ```bash
  pacman -Q | grep fwup
  fwupd 1.1.0-1
  ```
- Have you tried rebooting? Yes
- Are you using an NVMe disk? Yes
- Is secure boot enabled (only for the UEFI plugin)? No

**Comment by joakim-tjernlund** [comment]
This is very similar to what I see. I didn't see what the BIOS wrote while trying to update the BIOS
firmware though.

Then I downgraded  fwupd to 1.0.8 (which pulled in fwupdate 12) and retried(After setting
OverrideESPMountPoint=/boot), got some other strange error while running
fwupdmgr.
So I upgraded to fwupd 1.1.0 again and retried and now it WORKED.
Strangely I had some more file in ESP:
```
boot # ls -R EFI
EFI:
./  ../  BOOT/  EFI/  gentoo/

EFI/BOOT:
./  ../  BOOTX64.EFI*

EFI/EFI:
./  ../  gentoo/

EFI/EFI/gentoo:
./  ../  fw/  fwupx64.efi*

EFI/EFI/gentoo/fw:
./  ../

EFI/gentoo:
./  ../  fw/  fwupdx64.efi*

EFI/gentoo/fw:
./  ../  fwupdate-gnmj5U.cap*
```

There seem to be some misunderstanding where the files are stored.

**Comment by hughsie** [comment]
`EFI/EFI/` looks fishy indeed

**Comment by joakim-tjernlund** [comment]
yes, but it seems this path(EFI/EFI) was the one that made it work though.
I figured I would redo the install to see more details but fwupd will not let me reinstall
the same BIOS version(tried  fwupdmgr update --allow-reinstall):
fwupdmgr update --allow-reinstall
No upgrades for 20L7001UMX System Firmware, current is 0.1.25: 0.1.25=same

**Comment by superm1** [comment]
@patricius972 What version of fwupdate are you using when successful with 1.0.8?  12?
I think a useful debugging tactic would be to take the EFI binary from fwupd 1.1.0 (fwupdx64.efi) and *overwrite* the one used in fwupdate (fwupx64.efi) before flashing with 1.0.8.  That would at least help to narrow down if the problem of the malformed GUID is happening with fwupd or the EFI application.

**Comment by patricius972** [comment]
Yes it was fwupdate 12, I did not reboot under 1.0.8, and i verified the only efi was the one from 1.1.0 when i rebooted. Probably something to ask to the ones who did not have a successful update yet. Seems like at the creation of the cap file before reboot. Interestingly, the file from 1.0.8 did not get deleted. 

EFI
    ├── arch
    │   ├── fw
    │   │   └── fwupdate-AlqR39.cap
    │   └── fwupdx64.efi

I can try to do stuff with that file you want. The other one got deleted.

**Comment by superm1** [comment]
Assuming Lenovo's firmware doesn't complain, you should be able to reinstall from the CAB file with `--allow-reinstall`

**Comment by joakim-tjernlund** [comment]
--allow-reinstall does not work. fwupd just says:
fwupdmgr update --allow-reinstall
No upgrades for 20L7001UMX System Firmware, current is 0.1.25: 0.1.25=same

**Comment by superm1** [comment]
You have to download the CAB file and use `install` with `--allow-reinstall`

**Comment by ckoehn** [comment]
Any steps I can do to provide more debug information? (@joakim-tjernlund somehow took over my bug report ...)

**Comment by hughsie** [comment]
@ckoehn If you do `/usr/libexec/fwupd/fwupdate --set-debug` then retry the update, then `/usr/libexec/fwupd/fwupdate --log` what is displayed please?

**Comment by ckoehn** [comment]
@hughsie 
```
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:464:find_updates(): Found update fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7-0
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1286:efi_main(): Adding new capsule
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:575:search_file(): Searching Device Path: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)/\EFI\manjaro\fw\fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7.cap ...
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:603:search_file(): Device Path prepared: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:615:search_file(): Device supporting SFSP: PciRoot(0)/Pci(0x1D,0x2)/Pci(0x0,0x0)/Path(131,23,0x01000000002538BC61B4F53184012C00)/HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:622:search_file(): Comparing: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC) and PciRoot(0)/Pci(0x1D,0x2)/Pci(0x0,0x0)/Path(131,23,0x01000000002538BC61B4F53184012C00)/HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:622:search_file(): Comparing: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC) and Pci(0x1D,0x2)/Pci(0x0,0x0)/Path(131,23,0x01000000002538BC61B4F53184012C00)/HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:622:search_file(): Comparing: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC) and Pci(0x0,0x0)/Path(131,23,0x01000000002538BC61B4F53184012C00)/HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:622:search_file(): Comparing: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC) and Path(131,23,0x01000000002538BC61B4F53184012C00)/HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:622:search_file(): Comparing: HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC) and HD(Part4,Sig2307B9C5-536E-4C46-A31F-833EB8A3A0AC)
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:632:search_file(): Match up! Returning \EFI\manjaro\fw\fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7.cap
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:643:search_file(): File \EFI\manjaro\fw\fwupd-4e06f4ae-ab2e-4804-9a23-888e596a31e7.cap searched
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:704:open_file(): Found device
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:711:open_file(): Found volume
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:719:open_file(): Found file
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1046:add_capsule(): Read file; 9417280 bytes
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1047:add_capsule(): updates guid: G0
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1048:add_capsule(): File guid: 4E06F4AE-AB2E-4804-9A23-888E596A31E7
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1082:add_capsule(): Image does not have embedded header
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1084:add_capsule(): Allocating 9417308 for capsule header.
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1300:efi_main(): n_updates: 1
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1150:apply_capsules(): QueryCapsuleCapabilities: Unsupported max: 1666129087 reset:1
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1151:apply_capsules(): Capsules: 1
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1157:apply_capsules(): Could not apply capsule update: Not Found
../fwupd-1.1.0/plugins/uefi/efi/fwupdate.c:1319:efi_main(): fwupdate: Could not apply capsules: Not Found
```

**Comment by superm1** [comment]
@hughsie seeing that above log the updates GUID being wrong stands out to me.  Is the packing in https://github.com/hughsie/fwupd/blob/03aead9fe7dfd1bae90467f7ec2c724a017bbdba/plugins/uefi/fu-uefi-common.h#L52 done wrong?  Traditionally I've seen the attribute for packaging at the end of the struct definition (and that's how [fwupdate ](https://github.com/rhboot/fwupdate/blob/0972a58617ee02b6c2db0daaef99ae7542cc00b6/include/fwup-efi.h#L52)did it).

**Comment by hughsie** [comment]
4e06.. is the correct guid, no? I think the padding attribute is fine for a typedefed struct.

**Comment by superm1** [comment]
This part:
`add_capsule(): updates guid: G0`

**Comment by hughsie** [comment]
`%g` is a double or a GUID? `G0` is a weird double, and and even weirder GUID...

**Comment by ckoehn** [comment]
I'm not sure I will have time for this. Do you have plans to craft a new release any time soon? Would be easier to just get it via the package manager instead of compiling it myself.

**Comment by hughsie** [comment]
Yup, I'm planning a release in the next few days. We're just doing the last few reviews and tests before we press the button.

**Comment by ndechesne** [comment]
I am seeing the exact same issue, using archlinux on T460s:

$ sudo /usr/lib/fwupd/fwupdate --info
Information for the update status entry 0:
  Information Version: 7
  Firmware GUID: {00000000-0000-0000-0000-000000000000}
  Capsule Flags: 0x00000000x
  Hardware Instance: 0
  Update Status: attempted
  Capsule File Path: /EFI/arch/fw/fwupd-42f29620-3d63-4f09-950b-9b7055570f28.cap

To be honest, I am a little worried about doing a master branch build/test, as this is my main work machine , and it was my first attempt at making a firmware update as well... that moment when the machines reboot was already too much stress for me today.. ;-)

**Comment by hughsie** [comment]
Okay, I'll close this now, but please re-open if 1.1.1 doesn't fix things.

**Comment by kes31** [comment]
For me I could only fix this problem by marking the esp partition as esp with gparted.

**Comment by nicknefarious** [comment]
For what it's worth to others (great help to me), @kes31's advice above fixed things for me. My ESP partition was marked as **msftdata** for some reason. Changing the flag to **ESP** (also automatically added **boot** flag), using gparted, and then running the `fwupdmgr update` and everything worked as expected. As always, a few sweaty moments as it rebooted, and the screen went blank, but all was good. I had tried installing using:-
1. `fwupdmgr update` with the files downloaded from Linux Vendor Firmware Service (LVFS) - using `fwupdmgr refresh` and `fwupdmgr get-updates` and also
2. `fwupdmgr install N1CET82W.cab` where N1CET82W.cab, is the .cab file extracted from the .zip archive downloaded from Lenovo T460S Official Support page https://pcsupport.lenovo.com/au/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t460s/20f9/20f9cto1ww/pc0cmrzl/downloads/ds112117-bios-update-utility-bootable-cd-for-windows-10-81-7-64-bit-7-32-bit-linux-thinkpad-t460s - My laptop is T460s running Manjaro.
Using both of these methods, it looked like it was going to update, rebooted, but just rebooted without successfully completing the update.
