### ISSUE TITLE
/sys/firmware/efi/efivars: Read-only file system

### ISSUE THREAD

**Issue by joakim-tjernlund** [hughsie/fwupd#625]
Gentoo always mount efivars readonly so fwupdmgr fails with:
Error opening file “/sys/firmware/efi/efivars/fwupd-ebfe8df8-dee7-4692-a721-cbcf5095c5cf-0-0abba7dc-e516-4167-bbf5-4d9d1c739416”: Read-only file system
Unless one manually remonts efivars rw.

Could fwupdmgr remount efivvars automatically instead?

**Comment by superm1** [comment]
That seems like it's going to be generally problematic.  For example, `efibootmgr` is going to fail as well if efivars is mounted read only all the time.

**Comment by hughsie** [comment]
Why does it mount it ro? That seems like a bug. We should probably detect that and not offer any updates in that case.

**Comment by joakim-tjernlund** [comment]
It is intentional as there is a possibility to "brick/shoot your in the foot" , say some script/admin
does rm -rf in efivars

There is a similar RFE for efibootmgt too:
https://github.com/rhboot/efibootmgr/issues/76

**Comment by hughsie** [comment]
No, that's not possible anymore. Files in a rw efivars mount are immutable by default.

**Comment by superm1** [comment]
Been that way for a long time too now.

https://github.com/torvalds/linux/commit/ed8b0de5a33d2a2557dce7f9429dca8cb5bc5879

**Comment by ArchangeGabriel** [comment]
@superm1 Some news travel slowly… People who bricked their laptop because of this made a lot of noise, and the immediate reaction from people was to switch to `ro`. News of the proper fix did not spread well and configs last long.

**Comment by superm1** [comment]
@ArchangeGabriel makes sense to me.  If you're aware of anywhere else that still does `RO`, please notify them.  I've mentioned this in the recent [OpenRC bug report](https://github.com/OpenRC/openrc/issues/238) on the topic.

At least from fwupd side it will show a very obvious `UpdateError` now that this is the reason that you can't do an update.
