### ISSUE TITLE
ESP detection doesn't work with autofs

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#660]
This bug was reported in [Debian ](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906216)from the 1.1.1 release.

> My ESP is mounted via autofs so that it's unmounted when not in use:
> 
>     $ grep /boot/efi /etc/fstab
>     PARTLABEL=joyeux-esp /boot/efi vfat umask=0077,x-systemd.automount,x-systemd.idle-timeout=10 0 2
> 
> This leads to:
> 
>     # /usr/lib/fwupd/fwupdate --info 
>     Unable to determine EFI system partition location, override using --esp-path
> 
>     # /usr/lib/fwupd/fwupdate --info --esp-path /boot/efi
>     ESP specified was not valid: /boot/efi has an invalid type, expected vfat|ntfs|exfat
> 
> fwupd seems to be looking through existing mounts for one of the correct
> type, which won't work where the ESP is mounted via autofs, since it's
> not mounted yet...
>

**Comment by hughsie** [comment]
I'm not sure what we should do here. I'm not terribly happy parsing fstab. Ideas?

**Comment by superm1** [comment]
It seems that there should be a matching systemd unit (and systemd does parsing of /etc/fstab).
https://www.freedesktop.org/software/systemd/man/systemd.automount.html

I see two solutions:
1. Add `autofs` to the supported filesystem types.  Users who do this will have to use the ESP override and then it should work just fine for them.
2. "1" and "Simple" parsing for this scenario as a fallback if it's not mounted.  That should mean look for:
a. uncommented line
b. one of the 3 different supported strings in the second field of `/etc/fstab` 
c. `x-systemd.automount` in the fourth.

**Comment by hughsie** [comment]
> Add autofs to the supported filesystem types

If that works, that seems like the pragmatic choice to me.

**Comment by reversesh3ll** [comment]
I can confirm this is a bug on Arch using systemd-boot as well.

**Comment by superm1** [comment]
Can you please test this?

https://github.com/hughsie/fwupd/pull/661
