### ISSUE TITLE
Check Free Space on EFI Partition before reboot

### ISSUE THREAD

**Issue by mrdrogdrog** [hughsie/fwupd#670]
I tried to update my Thinkpad T480s's UEFI, but that failed several times.
Everything ran fine until the reboot.
The fwupd efi boot crashed after some seconds, showed an error message for a split second  and bootet back into my linux. I was able to read the error message using my phones camera.

The error message:
There wasn't enough space on my EFI-Partition.

So I moved the Windows Bootloader to a temporary place and tried again. Now everything is okay.

Please check if there is enough free space on the EFI-Partition before rebooting.
and
Please insert a 5-second-wait before rebooting in case of an error.

Thx :)

**Comment by hughsie** [comment]
> enough free space

How do we know the amount of free space the EFI updates needs? Do yo know if it decompresses to the ESP or anything like that? I had assumed that if we write the .cap file then no further space was required.

**Comment by superm1** [comment]
This may not apply to Lenovo, but at least for Dell a "BIOS recovery" file is created that allows going back to the old BIOS in the event of a failure.  Maybe they're doing something similar?

If we're going to add in some safety checks for size I think the biggest size SPI part currently seen (32M) is a good starting point.

Regarding automatically rebooting, it's a little unclear which actually performed the reboot here - fwupd or the vendor binary.
Can you please show the error message screenshot you saw?  We can see who showed what message so we can know if control returned to fwupd such that increasing a reboot timeout would help.

**Comment by hughsie** [comment]
@superm1 so we could just call `statfs()` in `fu_uefi_check_esp_path()` -- right? If so would @mrdrogdrog like to work on a patch for this issue? We're happy to help if you get stuck.

**Comment by superm1** [comment]
Yeah that seems reasonable to me.
