### ISSUE TITLE
May need to move thunderbolt over to new daemon provided replug

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#730]
I was hoping to avoid doing this for 1.1.2, but I'm finding that if a Thunderbolt device is in the transaction the rest of the tree isn't back in time for composite_cleanup to work properly even with the commits from #728 which helped with just USB devices in the transaction

**Comment by hughsie** [comment]
Couldn't we just do a blocking sleep at the end of the thunderbolt update() method?

**Comment by superm1** [comment]
Actually it already blocks at the end waiting for the Thunderbolt device to come back.  Adding extra sleeping on top of that doesn't help because it's the other devices that disappear too.

The device IDs are invalid for other devices later in the transaction (I actually see an error that they're not found because usb_device_added didn't run again).

I'll experiment with some stuff in composite_prepare to set stuff up to wait for replug.

**Comment by superm1** [comment]
OK I think i've got something that will work from `composite_prepare`, we can put off thunderbolt move to the new replug stuff until after 1.1.2.
