### ISSUE TITLE
Lenovo L560 doesn't want to restart after firmware update with gnome app manager

### ISSUE THREAD

**Issue by bealdav** [hughsie/fwupd#754]
Thanks for work in this project, but

## INFO

- Operating system and version: Ubuntu 18.04 updated to last recent update
- How did you install fwupd : included by gnome : application manager UI
- Have you tried rebooting? Yes
- Are you using an NVMe disk? Impossible to check (computer doesn't work anymore, I don't know)
- Is secure boot enabled (only for the UEFI plugin)? No

- No dual boot : only linux
- computer : Lenovo L560

## PROBLEM

- After firmware update with gnome, I restarted my computer.
- While computer updating firmware (or at the end), a very very big and long long 'beep' happened. 
- Now my computer doesn't want to restart (only green light on start button): black screen, no access to bios or any program. No Fxx key works to restart it

What can I do ??

Thanks.

I'm in the 0.01 % of fails ;-)

https://blogs.gnome.org/hughsie/2018/09/07/3-million-firmware-files-and-counting/

Sorry for my  question, but have you an idea, what I can do ?

**Comment by hughsie** [comment]
Hi. When did this happen? The L560 BIOS update was pulled by Lenovo a week or so ago: https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1791407 so I'm confused why you were still offered the update even now. Can you try the recovery steps in the launchpad bug please.

**Comment by bealdav** [comment]
This event occurs on friday 7th september.

I'll read launchpad. Thanks

**Comment by hughsie** [comment]
Phew, I thought it was getting old firmware or something. Sorry this happened to you, this really isn't supposed to happen. I've let Lenovo know in no uncertain terms it can't happen again.

**Comment by bealdav** [comment]
I will try tomorrow, this guidance.

Thanks a lot
