### ISSUE TITLE
Missing messages in translations

### ISSUE THREAD

**Issue by Marv-CZ** [hughsie/fwupd#760]
Options
"Print the version number"
"Print verbose debug statements"
"Specify Vendor/Product ID(s) of DFU device"
"Specify the number of bytes per USB transfer"
"Force the action ignoring all warnings"
are not marked for translation in plugins/dfu/dfu-tool.c

**Comment by hughsie** [comment]
Oops! Would you be able to do a pull request with the strings marked for translation? Thanks.

**Comment by superm1** [comment]
merged in #762
