### ISSUE TITLE
Please support elogind, a standalone version of logind

### ISSUE THREAD

**Issue by a17r** [hughsie/fwupd#798]
It seems like all we would need is a patch to the build system to alternatively accept elogind. `HAVE_SYSTEMD` should probably be renamed to the more general `HAVE_LOGIND` in case the future brings further systemd support.

**Comment by superm1** [comment]
No conceptual opposition; patches welcome

**Comment by superm1** [comment]
If you (or someone else chooses to do this), please do note that `HAVE_SYSTEMD` is also going to be used by PR #787.  If a patch is created to the build system to accept elogind, please create an additional `HAVE_LOGIND` and the place that it makes sense in `src/fu-util.c` do something like `defined(HAVE_SYSTEMD) || defined(HAVE_LOGIND)`
