### ISSUE TITLE
Regression: First run of fwupdmgr shows no devices

### ISSUE THREAD

**Issue by sourcejedi** [hughsie/fwupd#82]
As requested in #79:

Here is output from `journalctl -f`, after modifying fwupd.service to run using -v.

fwupd.service was activated by `fwupdmgr get-devices`, which showed no devices.  A second call to `fwupdmgr get-devices` did show devices.  I believe this behaviour is not shown in the downstream package version fwupd-0.7.5-1.fc25.x86_64.

[log.txt](https://github.com/hughsie/fwupd/files/711716/log.txt)

**Comment by hughsie** [comment]
I can reproduce!
