### ISSUE TITLE
dfu-tool replace-data cannot change last byte

### ISSUE THREAD

**Issue by mobilinkd** [hughsie/fwupd#903]
To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
client version:	1.0.9
daemon version:	1.0.9
compile-time dependency versions
	appstream-glib:	0.7.11
	gusb:	0.3.0
	fwupdate:	11
	efivar:	35
```

Please answer the following questions:

- Operating system and version: Linux Fedora 28
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): dnf install
- Have you tried rebooting? no
- Are you using an NVMe disk? no
- Is secure boot enabled (only for the UEFI plugin)? NA

Search and replace seems to have an off-by-one error.

I cannot replace the last byte of a dfuse file.

```shell
$ dfu-tool replace-data otp.dfu 1115000000000101 1115000000000001
search string was not found
```
I can replace the last N-1 bytes of a file, but if I try to include the last byte, the replace-data command claims the string is not found.  It is, in fact, there.  I have a 64-bit serial number that I would like to program into the device OTP and this seemed like a nice way to do that.  Unfortunately, the serial number is the last 8 bytes of a 24-byte data block.  I can only change 7 of the 8 bytes.

The file type does not seem to impact the problem.

To reproduce:
Create an Intel hex file called test.ihex containing 8 bytes of data.
```ihex
:020000041fffdc
:08700000111500000000000161
:00000001FF
```
Note that the data contents of this file are these 8 bytes -> 11 15 00 00 00 00 00 01.
Now attempt to replace the last 4 bytes.
```shell
$ dfu-tool replace-data test.ihex 00000001 00000002
search string was not found

Usage:
...
```
If you search and replace the first 7 bytes "11 15 00 00 00 00 00", it will succeed.

```shell
$ dfu-tool replace-data test.ihex 11150000000000 11150000000001
Replacing 7 bytes @0x0000
```

**Comment by hughsie** [comment]
Okay, all fixed and backported into the stable branch. Thanks for the detailed debugging, it made fixing this easy. Are you planning on shipping updates that use the fwupd dfu plugin? If so, do you need quirks added for your VID/PID too? If you're interested in shipping firmware on the LVFS as well, please send me an email and I'll set you up with a vendor account.
