### ISSUE TITLE
fwupd needs pango ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [hughsie/fwupd#910]
Seem like fwupd needs pango, see:
 https://bugs.gentoo.org/671096
Seems a bit odd that a cli/daemon service needs X11 related pkgs ?

**Comment by hughsie** [comment]
You need pango if you want to generate the BMPs required for the firmware upgrade splash.

**Comment by joakim-tjernlund** [comment]
I see, would be nice if BMP support is configurable. A mininal system will not have X11 at all.

**Comment by hughsie** [comment]
You only need pango support for _building_ fwupd, on the runtime deployment it's not required.

**Comment by joakim-tjernlund** [comment]
I see, but on Gentoo one builds pkg from source so one still needs X11.

**Comment by hughsie** [comment]
Right, I don't think it makes sense to build the system using the dependencies you're going to be using for deployment. fwupd requires gcc for building, but not for runtime.
