### ISSUE TITLE
useless error message: "Started with an incompatible locale!"

### ISSUE THREAD

**Issue by michich** [hughsie/fwupd#912]
fwupd logs this error on start:
```
led 03 09:37:39 localhost.localdomain fwupd[1536]: Started with an incompatible locale!
```
The error is not fatal, the daemon continues starting.
The message is not useful. It does not say what feature makes the current locale incompatible, what consequences to expect, or how to fix it.
My locale is cs_CZ.UTF-8. Looking at the code, it checks the formatting of numbers.
Perhaps it would make sense, instead of reporting an error, to do this in main()?:
```C
setlocale (LC_ALL, "");
setlocale (LC_NUMERIC, "C"); /* or "C.UTF-8" */
```

Version:
```shell
# fwupdmgr --version
client version:	1.2.2
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
Failed to connect to daemon: Chyba při volání StartServiceByName pro org.freedesktop.fwupd: Časový limit vypršel
```
(The daemon start error is unrelated, and already reported in issue #909.)

- Operating system and version:
Fedora Silverblue, Rawhide.20190101.n.0 (2019-01-01T06:59:21Z)
fwupd-1.2.2-1.fc30.x86_64

**Comment by michich** [comment]
Services get started with the system-wide locale settings from `/etc/locale.conf`.
Personally I wouldn't mind if services ran always in `C.UTF-8`, but that's not the current state.

**Comment by francoism90** [comment]
I'm also having the same issue:
```
$ cat /etc/locale.conf                                                                                                                      ✔ 
LANG=en_US.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_COLLATE=nl_NL.UTF-8
LC_CTYPE=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MONETARY=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_NUMERIC=nl_NL.UTF-8
LC_PAPER=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
```

**Comment by hughsie** [comment]
I guess we could do:

    setlocale (LC_ALL, "");
    setlocale (LC_NUMERIC, "C.UTF-8");

Although, maybe just removing the warning is the right thing to do. @superm1?

**Comment by superm1** [comment]
I do think we'll need this information to help identify future problems like the ebitdo one though.
So I guess based on these revelations we should downgrade the message to debug and also in the debug message indicate what the locale actually was.
