### ISSUE TITLE
fwupdmgr cant connect to server

### ISSUE THREAD

**Issue by amilopowers** [hughsie/fwupd#913]
```shell
$ fwupdmgr --version
**client version:	1.2.2
compile-time dependency versions
	gusb:	0.3.0
	efivar:	35
**
```
```shell
$ fwupdmgr get-devices
Fehler beim Aufruf von StartServiceByName für org.freedesktop.fwupd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.fwupd': timed out (service_start_timeout=25000ms)
```

```shell
$ efibootmgr -v
EFI variables are not supported on this system.
**This is only required if you use the UEFI plugin**
```

```shell
$ efivar -l | grep fw
efivar: error listing variables: Function not implemented
**This is only required if you use the UEFI plugin**
```

```shell
$ tree /boot
**INSERT OUTPUT HERE**
Did not find any.
**We're looking for any `.cap` files and the location of `fwupx64.efi`**
```

Please answer the following questions:

- Operating system and version: 
![grafik](https://user-images.githubusercontent.com/9914682/50688309-3923e980-1025-11e9-9dc5-3adc00540f70.png)

- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): Package installer "Pamac 6.4.0-1"
- Have you tried rebooting? yes
- Are you using an NVMe disk? yes
- Is secure boot enabled (only for the UEFI plugin)? It is diabled. I don't think that I use the plugin.

To me it loooks like the server isn't reachable. My internet connection works properly.

**Comment by hughsie** [comment]
You need the recently-released 1.2.3
