### ISSUE TITLE
Check battery level before updating devices

### ISSUE THREAD

**Issue by superm1** [hughsie/fwupd#925]
Right now there is only a check whether on AC power before running updates.  Since some updates are more than a few seconds to update and run in OS, it is potentially more dangerous to update them when the battery is low in case it runs out.  This is especially dangerous on devices that only have a single SPI bank or flash region.

So i was thinking that we should introduce another plugin (or patch to the existing `upower` one) that will examine `install_duration` when running on a laptop and if it's above some criteria then also require battery to be above some number.

Initial thoughts for numbers:
* Minimum install duration to activate: >30 seconds
* Minimum battery to install updates: 30%

Thoughts?

**Comment by hughsie** [comment]
I think that's perfectly sane. I'd say modifying the existing plugin makes sense.
