### ISSUE TITLE
fwupdmgr can't find TLS CA certs

### ISSUE THREAD

**Issue by shlevy** [hughsie/fwupd#95]
> $ fwupdmgr refresh
> Failed to download https://s3.amazonaws.com/lvfsbucket/downloads/firmware.xml.gz.asc: SSL handshake failed

This works with curl, though.

**Comment by hughsie** [comment]
I'm using libsoup to download this in fwupdmgr. What distro is this?

**Comment by shlevy** [comment]
NixOS

**Comment by superm1** [comment]
@shlevy Do you have glib_networking installed?  Noticed this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libsoup/default.nix#L35
which made me think it might not be a default for libsoup on NixOS.

**Comment by shlevy** [comment]
That was it, thanks!
